import type { TimelineTreeProject } from "../Components/TimelineTreeView";

export const timelineHierarchyMock: TimelineTreeProject[] = [
  {
    id: "project-alpha",
    name: "Project Alpha",
    status: "inprogress",
    progress: 58,
    moduleCount: 3,
    activityCount: 10,
    modules: [
      {
        id: "alpha-module-foundation",
        name: "Foundation",
        status: "completed",
        progress: 100,
        activityCount: 3,
        activities: [
          {
            id: "alpha-foundation-survey",
            code: "A-FND-01",
            name: "Site Survey",
            status: "completed",
            expectedDateLabel: "04 Jun 2026",
            hasDate: true,
            dependencies: [
              {
                id: "alpha-foundation-survey-report",
                code: "A-FND-01A",
                name: "Survey Report Approval",
                status: "completed",
                expectedDateLabel: "06 Jun 2026",
                hasDate: true,
                dependencies: [],
              },
            ],
          },
          {
            id: "alpha-foundation-layout",
            code: "A-FND-02",
            name: "Foundation Layout",
            status: "completed",
            expectedDateLabel: "10 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "alpha-foundation-handover",
            code: "A-FND-03",
            name: "Civil Handover",
            status: "completed",
            expectedDateLabel: "12 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
      {
        id: "alpha-module-installation",
        name: "Installation",
        status: "inprogress",
        progress: 54,
        activityCount: 4,
        activities: [
          {
            id: "alpha-install-rigging",
            code: "A-INS-01",
            name: "Rigging Mobilization",
            status: "completed",
            expectedDateLabel: "14 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "alpha-install-assembly",
            code: "A-INS-02",
            name: "Primary Assembly",
            status: "inprogress",
            expectedDateLabel: "18 Jun 2026",
            hasDate: true,
            dependencies: [
              {
                id: "alpha-install-assembly-checklist",
                code: "A-INS-02A",
                name: "Assembly QA Checklist",
                status: "inprogress",
                expectedDateLabel: "19 Jun 2026",
                hasDate: true,
                dependencies: [
                  {
                    id: "alpha-install-assembly-signoff",
                    code: "A-INS-02B",
                    name: "Supervisor Sign-off",
                    status: "yettostart",
                    expectedDateLabel: "20 Jun 2026",
                    hasDate: true,
                    dependencies: [],
                  },
                ],
              },
            ],
          },
          {
            id: "alpha-install-power",
            code: "A-INS-03",
            name: "Power Hook-up",
            status: "yettostart",
            expectedDateLabel: "22 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "alpha-install-test",
            code: "A-INS-04",
            name: "Dry Run Test",
            status: "yettostart",
            expectedDateLabel: "24 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
      {
        id: "alpha-module-closeout",
        name: "Closeout",
        status: "yettostart",
        progress: 0,
        activityCount: 3,
        activities: [
          {
            id: "alpha-close-documentation",
            code: "A-CLS-01",
            name: "Documentation Pack",
            status: "yettostart",
            expectedDateLabel: "27 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "alpha-close-training",
            code: "A-CLS-02",
            name: "Operator Training",
            status: "yettostart",
            expectedDateLabel: "29 Jun 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "alpha-close-handover",
            code: "A-CLS-03",
            name: "Final Handover",
            status: "yettostart",
            expectedDateLabel: "02 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
    ],
  },
  {
    id: "project-orion",
    name: "Project Orion",
    status: "completed",
    progress: 100,
    moduleCount: 2,
    activityCount: 6,
    modules: [
      {
        id: "orion-design",
        name: "Design Package",
        status: "completed",
        progress: 100,
        activityCount: 3,
        activities: [
          {
            id: "orion-design-brief",
            code: "O-DSN-01",
            name: "Design Brief Approval",
            status: "completed",
            expectedDateLabel: "12 May 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "orion-design-review",
            code: "O-DSN-02",
            name: "Multidisciplinary Review",
            status: "completed",
            expectedDateLabel: "17 May 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "orion-design-release",
            code: "O-DSN-03",
            name: "Issued for Construction",
            status: "completed",
            expectedDateLabel: "19 May 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
      {
        id: "orion-commissioning",
        name: "Commissioning",
        status: "completed",
        progress: 100,
        activityCount: 3,
        activities: [
          {
            id: "orion-commission-cold",
            code: "O-COM-01",
            name: "Cold Commissioning",
            status: "completed",
            expectedDateLabel: "25 May 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "orion-commission-hot",
            code: "O-COM-02",
            name: "Hot Commissioning",
            status: "completed",
            expectedDateLabel: "29 May 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "orion-commission-close",
            code: "O-COM-03",
            name: "Performance Handover",
            status: "completed",
            expectedDateLabel: "31 May 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
    ],
  },
  {
    id: "project-nova",
    name: "Project Nova",
    status: "yettostart",
    progress: 0,
    moduleCount: 2,
    activityCount: 5,
    modules: [
      {
        id: "nova-planning",
        name: "Planning",
        status: "yettostart",
        progress: 0,
        activityCount: 2,
        activities: [
          {
            id: "nova-plan-scope",
            code: "N-PLN-01",
            name: "Scope Freeze",
            status: "yettostart",
            expectedDateLabel: "08 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "nova-plan-budget",
            code: "N-PLN-02",
            name: "Budget Alignment",
            status: "yettostart",
            expectedDateLabel: "11 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
      {
        id: "nova-procurement",
        name: "Procurement",
        status: "yettostart",
        progress: 0,
        activityCount: 3,
        activities: [
          {
            id: "nova-prc-rfq",
            code: "N-PRC-01",
            name: "RFQ Release",
            status: "yettostart",
            expectedDateLabel: "14 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "nova-prc-bids",
            code: "N-PRC-02",
            name: "Bid Evaluation",
            status: "yettostart",
            expectedDateLabel: "18 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
          {
            id: "nova-prc-award",
            code: "N-PRC-03",
            name: "Award Recommendation",
            status: "yettostart",
            expectedDateLabel: "22 Jul 2026",
            hasDate: true,
            dependencies: [],
          },
        ],
      },
    ],
  },
];
